#!/usr/bin/bash

release=$(basename $(readlink -f /home/pi/openeo))
datetime=$(date +"%Y%m%d%H%M%S")
filename="debug_${release}_${datetime}.txt"

( echo "= PS"
echo "================="
ps -fLu pi
echo
echo "= NETSTAT"
echo "================="
netstat -4l
echo
echo "= JOURNALCTL"
echo "================="
journalctl |tail -250
echo
echo "= SYSTEMCTL"
echo "================="
systemctl status openeo

cat <<EOF | /usr/bin/python3 -
import sqlite3
from datetime import datetime

# Initialize SQLite DB and table
conn = sqlite3.connect("/home/pi/etc/config.db")
cursor = conn.cursor()

cursor.execute(f"SELECT module, key, value FROM configuration")
rows = cursor.fetchall()
print("\n= SQLITE CONFIG\n=================")
for row in rows:
    print(row)

cursor.execute(f"SELECT timestamp, message FROM log")
rows = cursor.fetchall()
print("\n= SQLITE LOG\n=================")
for (timestamp,message) in rows:
    print(datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S'),message)

EOF

) | tee $filename

echo
echo "================="
echo "= Compressing"
echo "================="
zip ${filename}.zip $filename 

echo
echo "================="
echo "= Attempting to upload debug report"
echo "================="
curl -X POST https://eo.scott.land/upload.cgi --data-binary @${filename}.zip -H "X-Filename: ${filename}.zip" -H "X-Key: ${filename}.zip" --http1.1 >/dev/null

echo
RC=$?
if [ $RC -eq 0 ]; then
    echo "Upload successful - filename $filename"
else
    echo "Upload failed (RC=$RC)- filename $filename"

fi

