name: Build-openeo
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
env:
  MY_IMAGE_NAME: "openeo"
  MY_IMAGE_DESC: "openeo"
  IMAGE_REGISTRY: "ghcr.io"
  STORAGE_DRIVER: "vfs"
  BUILDAH_ISOLATION: "chroot"
  BUILDAH_LAYERS: true      
  BUILDAH_PROGRESS: true



jobs:
  
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to registry
        run: |
          buildah login  --username=${{ github.actor }} --password=$REGISTRY_PASSWORD $IMAGE_REGISTRY
        env:
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set image tags
        id: tags
        run: |
          echo "IMAGE_TAGS=${{ github.sha }}" >> $GITHUB_ENV
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_TAGS=${{ github.sha }},latest" >> $GITHUB_ENV
          fi

      - name: Build Image
        run: |
          for tag in $(echo $IMAGE_TAGS | tr ',' '\n'); do
             buildah -t $IMAGE_REGISTRY/${{ github.repository }}:$tag \
              -f docker/Dockerfile .
          done

      - name: Push Image
        run: |
          for tag in $(echo $IMAGE_TAGS | tr ',' '\n'); do
            podman push $IMAGE_REGISTRY/${{ github.repository }}:$tag
          done
