name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - name: Create zip of repository
        run: |
          zip -r openeo-${{ steps.release.outputs.tag_name }}.zip . -x '*.git*' '.github*'
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: openeo-${{ steps.release.outputs.tag_name }}.zip
          asset_name: openeo-${{ steps.release.outputs.tag_name }}.zip
          tag: ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
